const $ = id => document.getElementById(id);
const canvas = $('planCanvas'), ctx = canvas.getContext('2d');
const defaultPoints = [{x:1,y:1},{x:6.7,y:1},{x:6.7,y:2.3},{x:5.4,y:2.3},{x:5.4,y:4.8},{x:6.7,y:4.8},{x:6.7,y:6.3},{x:1,y:6.3}];
let points = structuredClone(defaultPoints), selected = null, dragging = false, mode = 'select', zoom = 1;
const values = ['canvasPrice','reserve','profilePrice','installPrice','markup','spots','spotPrice','lightLine','lightLinePrice','chandelierPrice','pipePrice','lightPointPrice'];
const inputIds = [...values,'canvasType','canvasColor','profileType','clientName','clientPhone','clientAddress','clientNote','projectName'];
function fmt(n, digits=2){return new Intl.NumberFormat('ru-RU',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n)}
function money(n){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n)}
function area(){let s=0;for(let i=0;i<points.length;i++){let a=points[i],b=points[(i+1)%points.length];s+=a.x*b.y-b.x*a.y}return Math.abs(s)/2}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function perimeter(){return points.reduce((s,p,i)=>s+dist(p,points[(i+1)%points.length]),0)}
function selfIntersects(){function cross(a,b,c){return (b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x)}function hit(a,b,c,d){let x=cross(a,b,c),y=cross(a,b,d),z=cross(c,d,a),w=cross(c,d,b);return x*y<0&&z*w<0}for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){if(Math.abs(i-j)<2||Math.abs(i-j)===points.length-1)continue;if(hit(points[i],points[(i+1)%points.length],points[j],points[(j+1)%points.length]))return true}return false}
function transform(p){const scale=72*zoom, ox=canvas.width/2-3.85*scale, oy=canvas.height/2-3.65*scale;return{x:ox+p.x*scale,y:oy+p.y*scale}}
function untransform(p){const scale=72*zoom, ox=canvas.width/2-3.85*scale, oy=canvas.height/2-3.65*scale;return{x:(p.x-ox)/scale,y:(p.y-oy)/scale}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);const scale=72*zoom, origin=transform({x:0,y:0});ctx.strokeStyle='#edf0f5';ctx.lineWidth=1;for(let x=origin.x%scale;x<canvas.width;x+=scale){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=origin.y%scale;y<canvas.height;y+=scale){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}
const ps=points.map(transform);ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle='rgba(45,109,246,.13)';ctx.fill();ctx.strokeStyle='#2d6df6';ctx.lineWidth=3;ctx.stroke();ps.forEach((p,i)=>{let q=ps[(i+1)%ps.length],mid={x:(p.x+q.x)/2,y:(p.y+q.y)/2};ctx.fillStyle='rgba(255,255,255,.94)';ctx.fillRect(mid.x-27,mid.y-11,54,20);ctx.fillStyle='#42618e';ctx.font='12px Segoe UI';ctx.textAlign='center';ctx.fillText(fmt(dist(points[i],points[(i+1)%points.length]))+' м',mid.x,mid.y+4)});ps.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i===selected?9:7,0,Math.PI*2);ctx.fillStyle=i===selected?'#f49a32':'#fff';ctx.fill();ctx.strokeStyle='#2d6df6';ctx.lineWidth=3;ctx.stroke()});}
function totals(){let a=area(), p=perimeter(), reserve=+$('reserve').value||0, materialArea=a*(1+reserve/100), canvasCost=materialArea*(+$('canvasPrice').value||0), profileCost=p*(+$('profilePrice').value||0), install=a*(+$('installPrice').value||0), plan=planObjects||[], spotCount=plan.filter(o=>o.type==='spot').length, chandelierCount=plan.filter(o=>o.type==='chandelier').length, pipeCount=plan.filter(o=>o.type==='pipe').length, lightCount=plan.filter(o=>o.type==='light').length, ventCount=plan.filter(o=>o.type==='vent').length, corniceCount=plan.filter(o=>o.type==='cornice').length, trackCount=plan.filter(o=>o.type==='track').length, separatorCount=plan.filter(o=>o.type==='separator').length, manualSpots=+$('spots').value||0, spots=Math.max(manualSpots,spotCount)*(+$('spotPrice').value||0), line=(+$('lightLine').value||0)*(+$('lightLinePrice').value||0), chandeliers=chandelierCount*(+$('chandelierPrice').value||0), pipes=pipeCount*(+$('pipePrice').value||0), lightPoints=lightCount*(+$('lightPointPrice').value||0), fasteners=Math.ceil(p/.15), fastenerCost=fasteners*8, harpoonCost=p*32, insertCost=['Стандартный ПВХ','Алюминиевый'].includes($('profileType').value)?p*35:0, objectWorks=ventCount*550+corniceCount*600+trackCount*700+separatorCount*450, accessories=fastenerCost+harpoonCost+insertCost+objectWorks, subtotal=canvasCost+profileCost+install+spots+line+chandeliers+pipes+lightPoints+accessories, markup=subtotal*(+$('markup').value||0)/100;return{a,p,materialArea,canvasCost,profileCost,install,spots,line,chandeliers,pipes,lightPoints,spotCount,chandelierCount,pipeCount,lightCount,ventCount,corniceCount,trackCount,separatorCount,fasteners,fastenerCost,harpoonCost,insertCost,objectWorks,accessories,markup,total:subtotal+markup}}
function update(){let t=totals();$('areaValue').textContent=fmt(t.a)+' м²';$('perimeterValue').textContent=fmt(t.p)+' м';$('pointsValue').textContent=points.length;$('totalValue').textContent=money(t.total);$('zoomText').textContent=Math.round(zoom*100)+'%';$('lightingAdvice').textContent=`Рекомендация: для ${fmt(t.a)} м² обычно достаточно ${Math.max(1,Math.ceil(t.a/3.5))} точечных светильников. Указано: ${+$('spots').value||0}.`;let bad=selfIntersects()||t.a<1;let list=[['Контур замкнут',true],['Минимум 3 вершины',points.length>=3],['Нет пересечений линий',!selfIntersects()],['Площадь больше 1 м²',t.a>=1]];$('checkList').innerHTML=list.map(([x,ok])=>`<li class="${ok?'':'bad'}">${x}</li>`).join('');$('validation').textContent=bad?'Исправьте геометрию: контур пересекается или площадь слишком мала.':'';updateEstimate(t)}
function updateEstimate(t){$('estimateProject').textContent=$('projectName').value||'Проект потолка';$('estimateDate').textContent=new Date().toLocaleDateString('ru-RU');$('estimateClient').textContent=$('clientName').value||'Не указан';$('estimatePhone').textContent=$('clientPhone').value||'';const type=$('canvasType').selectedOptions[0].text, rows=[[`Полотно — ${type}`,`${fmt(t.materialArea)} м²`,+$('canvasPrice').value,t.canvasCost],['Профиль',`${fmt(t.p)} п.м.`,+$('profilePrice').value,t.profileCost],['Монтаж',`${fmt(t.a)} м²`,+$('installPrice').value,t.install]];if(t.spots)rows.push(['Точечные светильники',Math.max(+$('spots').value||0,t.spotCount),+$('spotPrice').value,t.spots]);if(t.line)rows.push(['Световая линия',`${$('lightLine').value} м`,$('lightLinePrice').value,t.line]);if(t.chandeliers)rows.push(['Люстры / закладные',t.chandelierCount,$('chandelierPrice').value,t.chandeliers]);if(t.pipes)rows.push(['Обходы труб',t.pipeCount,$('pipePrice').value,t.pipes]);if(t.lightPoints)rows.push(['Световые точки',t.lightCount,$('lightPointPrice').value,t.lightPoints]);if(t.accessories)rows.push(['Автокомплектация: гарпун, крепёж, вставка и доп. работы','по проекту','—',t.accessories]);if(t.markup)rows.push(['Наценка','—',`${$('markup').value}%`,t.markup]);$('estimateRows').innerHTML=rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${typeof r[2]==='number'?money(r[2]):r[2]}</td><td>${money(r[3])}</td></tr>`).join('');$('estimateTotal').innerHTML=`<tr><td colspan="3">Итого</td><td>${money(t.total)}</td></tr>`}
function canvasPos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{let m=canvasPos(e),ps=points.map(transform),near=ps.findIndex(p=>Math.hypot(p.x-m.x,p.y-m.y)<15);if(mode==='add'){let best={d:Infinity,i:0};for(let i=0;i<ps.length;i++){let a=ps[i],b=ps[(i+1)%ps.length],dx=b.x-a.x,dy=b.y-a.y,u=Math.max(0,Math.min(1,((m.x-a.x)*dx+(m.y-a.y)*dy)/(dx*dx+dy*dy))),q={x:a.x+u*dx,y:a.y+u*dy},d=Math.hypot(q.x-m.x,q.y-m.y);if(d<best.d)best={d,i}}if(best.d<24){points.splice(best.i+1,0,untransform(m));selected=best.i+1;mode='select';$('addPointTool').classList.remove('active');$('selectTool').classList.add('active');draw();update();}return}if(near>=0){selected=near;dragging=true;canvas.setPointerCapture(e.pointerId);draw()}});
canvas.addEventListener('pointermove',e=>{if(!dragging||selected===null)return;points[selected]=untransform(canvasPos(e));draw();update()});canvas.addEventListener('pointerup',()=>dragging=false);
function switchView(name){['drawing','materials','catalog','estimate','measure','check','client'].forEach(v=>$(v+'View').classList.toggle('hidden',v!==name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('drawingTools').style.display=name==='drawing'?'block':'none';$('templatesTools').style.display=name==='drawing'?'block':'none';if(name==='measure')renderMeasureSheet();if(name==='catalog')renderCatalog();if(name==='check')renderPreflight()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('goEstimate').onclick=()=>switchView('estimate');$('selectTool').onclick=()=>{mode='select';$('selectTool').classList.add('active');$('addPointTool').classList.remove('active')};$('addPointTool').onclick=()=>{mode='add';$('addPointTool').classList.add('active');$('selectTool').classList.remove('active');$('canvasTip').textContent='Нажмите на любую линию контура, чтобы добавить вершину'};$('deletePoint').onclick=()=>{if(selected!==null&&points.length>3){points.splice(selected,1);selected=null;draw();update()}else toast('Выберите вершину. В контуре должно остаться минимум 3 точки.')} ;$('resetPlan').onclick=()=>{points=structuredClone(defaultPoints);selected=null;zoom=1;draw();update();toast('Демонстрационный план восстановлен')};$('zoomIn').onclick=()=>{zoom=Math.min(1.7,zoom+.1);draw();update()};$('zoomOut').onclick=()=>{zoom=Math.max(.55,zoom-.1);draw();update()};$('fitPlan').onclick=()=>{zoom=1;draw();update()};inputIds.forEach(id=>$(id).addEventListener('input',update));
function snapshot(){let data={points,zoom,inputs:Object.fromEntries(inputIds.map(id=>[id,$(id).value])),saved:new Date().toLocaleString('ru-RU')};return data}function apply(data){points=data.points||structuredClone(defaultPoints);zoom=data.zoom||1;Object.entries(data.inputs||{}).forEach(([id,v])=>{if($(id))$(id).value=v});draw();update();switchView('drawing')}
function toast(text){let el=$('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}function renderSaved(){let arr=JSON.parse(localStorage.getItem('ceiling-projects')||'[]');$('savedList').innerHTML=arr.length?arr.map((p,i)=>`<button class="saved-item" data-index="${i}">${p.inputs.projectName||'Без названия'}<small>${p.saved}</small></button>`).join(''):'<p class="hint">Сохранённых проектов пока нет</p>';document.querySelectorAll('.saved-item').forEach(b=>b.onclick=()=>{apply(arr[+b.dataset.index]);toast('Проект открыт')})}$('saveProject').onclick=()=>{let arr=JSON.parse(localStorage.getItem('ceiling-projects')||'[]');arr.unshift(snapshot());localStorage.setItem('ceiling-projects',JSON.stringify(arr.slice(0,12)));renderSaved();$('saveState').textContent='✓ Сохранено';toast('Проект сохранён в этом браузере')};$('newProject').onclick=()=>{apply({points:structuredClone(defaultPoints),zoom:1,inputs:{projectName:'Новый проект'}});toast('Создан новый проект')};$('clearSaved').onclick=()=>{localStorage.removeItem('ceiling-projects');renderSaved();toast('Список проектов очищен')};$('printEstimate').onclick=()=>window.print();
draw();update();renderSaved();

// Производственный режим: основной замер задаётся длинами сторон и внутренними углами.
// Диагонали используются как контроль и для сложной геометрии.
var diagonals = [];
var angleClosure = null;
var baseUpdate = update;
update = function(){ baseUpdate(); if(angleClosure!==null){$('checkList').insertAdjacentHTML('beforeend',`<li class="${angleClosure<.03?'':'bad'}">Замыкание по углам: ${angleClosure<.03?'в норме':'расхождение '+angleClosure.toFixed(2)+' м'}</li>`);} renderMeasurements(); renderDiagonals(); renderMeasureSheet(); };
function vertexName(i){ return String.fromCharCode(65 + (i % 26)) + (i > 25 ? Math.floor(i / 26) : ''); }
function interiorAngle(i){
  const prev=points[(i-1+points.length)%points.length], cur=points[i], next=points[(i+1)%points.length];
  const a={x:cur.x-prev.x,y:cur.y-prev.y}, b={x:next.x-cur.x,y:next.y-cur.y};
  let turn=Math.atan2(a.x*b.y-a.y*b.x,a.x*b.x+a.y*b.y)*180/Math.PI;
  if(turn<0) turn+=360;
  return 180-turn;
}
function renderMeasurements(){
  const host=$('angleMeasurements'); if(!host) return;
  host.innerHTML=points.map((p,i)=>`<div class="measure-row"><span>${vertexName(i)} → ${vertexName((i+1)%points.length)}</span><label>Сторона, м<input class="side-input" data-index="${i}" type="number" min="0.01" step="0.01" value="${dist(p,points[(i+1)%points.length]).toFixed(2)}" /></label><label>Угол в ${vertexName(i)}, °<input class="angle-input" data-index="${i}" type="number" min="1" max="359" step="0.1" value="${interiorAngle(i).toFixed(1)}" /></label></div>`).join('');
  const options=points.map((_,i)=>`<option value="${i}">${vertexName(i)}</option>`).join('');
  $('diagonalFrom').innerHTML=options; $('diagonalTo').innerHTML=options;
  if(points.length>2) $('diagonalTo').value='2';
}
function renderDiagonals(){
  const host=$('diagonalList'); if(!host) return;
  host.innerHTML=diagonals.map((d,i)=>{const actual=dist(points[d.from],points[d.to]), delta=Math.abs(actual-d.length);return `<div class="diagonal-item"><span>${vertexName(d.from)} — ${vertexName(d.to)}: ${d.length.toFixed(2)} м <b>${delta<.03?'✓':'расхождение '+delta.toFixed(2)+' м'}</b></span><button data-diagonal="${i}">Удалить</button></div>`}).join('');
  host.querySelectorAll('button[data-diagonal]').forEach(b=>b.onclick=()=>{diagonals.splice(+b.dataset.diagonal,1);renderDiagonals();});
}
function applyAngleMeasure(){
  const sides=[...document.querySelectorAll('.side-input')].map(x=>+x.value);
  const angles=[...document.querySelectorAll('.angle-input')].map(x=>+x.value);
  if(sides.some(x=>!Number.isFinite(x)||x<=0)||angles.some(x=>!Number.isFinite(x)||x<=0||x>=360)){toast('Проверьте длины сторон и значения углов');return;}
  const built=[{x:0,y:0}]; let heading=0;
  built.push({x:sides[0],y:0});
  for(let i=1;i<sides.length-1;i++){ heading+=(180-angles[i])*Math.PI/180; const last=built[built.length-1];built.push({x:last.x+sides[i]*Math.cos(heading),y:last.y+sides[i]*Math.sin(heading)}); }
  heading+=(180-angles[sides.length-1])*Math.PI/180; const last=built[built.length-1]; const finish={x:last.x+sides[sides.length-1]*Math.cos(heading),y:last.y+sides[sides.length-1]*Math.sin(heading)};
  angleClosure=Math.hypot(finish.x,finish.y); points=built; selected=null; draw();update();
  toast(angleClosure<.03?'Контур по углам построен и замкнут':'Контур построен. Проверьте расхождение замыкания');
}
$('anglesMode').onclick=()=>{$('anglesPanel').classList.remove('hidden');$('triangulationPanel').classList.add('hidden');$('anglesMode').classList.add('active');$('triangulationMode').classList.remove('active');};
$('triangulationMode').onclick=()=>{$('anglesPanel').classList.add('hidden');$('triangulationPanel').classList.remove('hidden');$('triangulationMode').classList.add('active');$('anglesMode').classList.remove('active');renderMeasurements();renderDiagonals();};
$('applyAngles').onclick=applyAngleMeasure;
$('addDiagonal').onclick=()=>{const from=+$('diagonalFrom').value,to=+$('diagonalTo').value,length=+$('diagonalLength').value;if(from===to||!length){toast('Выберите разные вершины и укажите длину диагонали');return;}diagonals.push({from,to,length});renderDiagonals();toast('Диагональ добавлена к проверке');};
function renderMeasureSheet(){
  if(!$('measureCanvas'))return; const t=totals();
  $('measureProjectName').textContent=$('projectName').value||'Проект потолка';$('measureCreated').textContent='Сформирован: '+new Date().toLocaleDateString('ru-RU');$('measureClient').textContent=$('clientName').value||'Не указан';$('measureAddress').textContent=$('clientAddress').value||'Не указан';$('measureMaterial').textContent=$('canvasType').selectedOptions[0].text+' · '+$('canvasColor').value;$('measureMetrics').textContent=fmt(t.a)+' м² / '+fmt(t.p)+' м';
  $('measureSideRows').innerHTML=points.map((p,i)=>`<tr><td>${vertexName(i)}–${vertexName((i+1)%points.length)}</td><td>${fmt(dist(p,points[(i+1)%points.length]))} м</td><td>${fmt(interiorAngle(i),1)}°</td></tr>`).join('');
  $('measureDiagonalRows').innerHTML=diagonals.length?diagonals.map(d=>{const delta=Math.abs(dist(points[d.from],points[d.to])-d.length);return `<tr><td>${vertexName(d.from)}–${vertexName(d.to)}</td><td>${fmt(d.length)} м</td><td>${delta<.03?'✓': 'Δ '+fmt(delta)+' м'}</td></tr>`}).join(''):'<tr><td colspan="3">Контрольные диагонали не добавлены</td></tr>';
  const c=$('measureCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);let minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)),scale=Math.min((c.width-100)/Math.max(maxX-minX,.5),(c.height-100)/Math.max(maxY-minY,.5));const map=p=>({x:50+(p.x-minX)*scale,y:50+(p.y-minY)*scale});const ps=points.map(map);x.beginPath();ps.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.fillStyle='rgba(45,109,246,.08)';x.fill();x.strokeStyle='#243b69';x.lineWidth=2;x.stroke();diagonals.forEach(d=>{let a=ps[d.from],b=ps[d.to];x.setLineDash([5,4]);x.strokeStyle='#e07b45';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();x.setLineDash([])});ps.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,8,0,Math.PI*2);x.fillStyle='#2d6df6';x.fill();x.fillStyle='#fff';x.font='bold 11px Arial';x.textAlign='center';x.fillText(vertexName(i),p.x,p.y+4)});
}
$('printMeasure').onclick=()=>{document.body.classList.add('print-measure');window.print();setTimeout(()=>document.body.classList.remove('print-measure'),1000);};
renderMeasurements();renderDiagonals();

// Объекты на плане: используются в рабочем чертеже и попадают в замерный лист.
var planObjects = [];
var baseDrawPlan = draw;
draw = function(){baseDrawPlan();drawPlanObjects();};
function objectMeta(type){return {spot:{name:'Точечный светильник',color:'#f2a239',mark:'●'},chandelier:{name:'Люстра',color:'#825ae8',mark:'✦'},pipe:{name:'Обвод трубы',color:'#d96155',mark:'○'},light:{name:'Световая точка',color:'#19a6bd',mark:'━'}}[type];}
function drawPlanObjects(){planObjects.forEach(o=>{const p=transform(o),m=objectMeta(o.type);ctx.save();ctx.strokeStyle=m.color;ctx.fillStyle=m.color;ctx.lineWidth=4;if(o.x2!==undefined){const q=transform({x:o.x2,y:o.y2});ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.font='bold 16px Segoe UI';ctx.textAlign='center';ctx.fillText(m.mark,(p.x+q.x)/2,(p.y+q.y)/2-10);}else{ctx.font='bold 22px Segoe UI';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(m.mark,p.x,p.y);}ctx.restore();});}
document.querySelectorAll('[data-object-tool]').forEach(b=>b.onclick=()=>{mode='object:'+b.dataset.objectTool;document.querySelectorAll('[data-object-tool],#selectTool,#addPointTool').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('canvasTip').textContent='Нажмите внутри контура, чтобы разместить объект';});
function insidePlan(p){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x))inside=!inside;}return inside;}
function alignLineToRoom(a,b){let best={d:Infinity,a:null,b:null,q:null};for(let i=0;i<points.length;i++){const s=points[i],e=points[(i+1)%points.length],dx=e.x-s.x,dy=e.y-s.y,l2=dx*dx+dy*dy,u=Math.max(0,Math.min(1,((a.x+b.x)/2-s.x)*dx+((a.y+b.y)/2-s.y)*dy)/l2),q={x:s.x+u*dx,y:s.y+u*dy},d=Math.hypot((a.x+b.x)/2-q.x,(a.y+b.y)/2-q.y);if(d<best.d)best={d,a:s,b:e,q};}const dx=best.b.x-best.a.x,dy=best.b.y-best.a.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len,half=Math.hypot(b.x-a.x,b.y-a.y)/2,center=best.q;return{x:center.x-ux*half,y:center.y-uy*half,x2:center.x+ux*half,y2:center.y+uy*half};}
var pendingLine=null;
canvas.addEventListener('pointerdown',()=>{const last=planObjects[planObjects.length-1];if(last&&last.x2!==undefined&&!last.geometryAligned){const aligned=alignLineToRoom({x:last.x,y:last.y},{x:last.x2,y:last.y2});Object.assign(last,aligned,{geometryAligned:true});draw();update();}});
canvas.addEventListener('pointerdown',e=>{if(!mode.startsWith('object:'))return;const p=untransform(canvasPos(e)),type=mode.split(':')[1];if(!insidePlan(p)){toast('Объект можно разместить только внутри контура');return;}if(['light','cornice','track','separator'].includes(type)){if(!pendingLine){pendingLine={type,x:p.x,y:p.y};$('canvasTip').textContent='Укажите вторую точку линии';return;}planObjects.push({...pendingLine,x2:p.x,y2:p.y});pendingLine=null;toast('Линейный объект добавлен');}else{planObjects.push({type,x:p.x,y:p.y});toast('Объект добавлен на план');}mode='select';document.querySelectorAll('[data-object-tool]').forEach(x=>x.classList.remove('active'));$('selectTool').classList.add('active');$('canvasTip').textContent='Тяните за маркеры, чтобы изменить форму комнаты';draw();update();});
var productionUpdate = update;
update = function(){productionUpdate();const t=totals();$('objectsPriceSummary').textContent=`● ${t.spotCount} · ✦ ${t.chandelierCount} · ◌ ${t.pipeCount} · ━ ${t.lightCount}`;$('lightingAdvice').textContent=`Рекомендация: для ${fmt(t.a)} м² обычно достаточно ${Math.max(1,Math.ceil(t.a/3.5))} точечных светильников. На плане: ${t.spotCount}; в смете: ${Math.max(+$('spots').value||0,t.spotCount)}.`;renderObjectRows();renderObjectManager();};
function renderObjectRows(){const host=$('measureObjectRows');if(!host)return;host.innerHTML=planObjects.length?planObjects.map(o=>{const m=objectMeta(o.type);return `<tr><td>${m.name}</td><td>X ${fmt(o.x)} · Y ${fmt(o.y)}</td></tr>`}).join(''):'<tr><td colspan="2">Объекты не добавлены</td></tr>';}
function renderObjectManager(){const host=$('planObjectsList');if(!host)return;const counts=planObjects.reduce((r,o)=>(r[o.type]=(r[o.type]||0)+1,r),{});$('objectsSummary').textContent=planObjects.length?`${planObjects.length} шт. · светильников: ${counts.spot||0}`:'Нет объектов';host.innerHTML=planObjects.length?planObjects.map((o,i)=>{const m=objectMeta(o.type);return `<div class="plan-object-row"><div><strong style="color:${m.color}">${m.mark} ${m.name}</strong><small>Координаты: ${fmt(o.x)} × ${fmt(o.y)} м</small></div><button data-remove-object="${i}" title="Удалить объект">×</button></div>`}).join(''):'<p class="empty-objects">Добавьте объект инструментом слева, затем он появится здесь.</p>';host.querySelectorAll('[data-remove-object]').forEach(b=>b.onclick=()=>{planObjects.splice(+b.dataset.removeObject,1);draw();update();toast('Объект удалён');});}
var measureSheetBase = renderMeasureSheet;
renderMeasureSheet = function(){measureSheetBase();renderObjectRows();const c=$('measureCanvas');if(!c||!planObjects.length)return;const x=c.getContext('2d');let minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)),scale=Math.min((c.width-100)/Math.max(maxX-minX,.5),(c.height-100)/Math.max(maxY-minY,.5));planObjects.forEach(o=>{const m=objectMeta(o.type),p={x:50+(o.x-minX)*scale,y:50+(o.y-minY)*scale};x.fillStyle=m.color;x.font='bold 19px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(m.mark,p.x,p.y);});};
function snapshot(){return {points,zoom,objects:planObjects,diagonals,angleClosure,inputs:Object.fromEntries(inputIds.map(id=>[id,$(id).value])),saved:new Date().toLocaleString('ru-RU')}}
function apply(data){points=data.points||structuredClone(defaultPoints);zoom=data.zoom||1;planObjects=data.objects||[];diagonals=data.diagonals||[];angleClosure=data.angleClosure??null;Object.entries(data.inputs||{}).forEach(([id,v])=>{if($(id))$(id).value=v});draw();update();switchView('drawing')}
$('resetPlan').addEventListener('click',()=>{planObjects=[];diagonals=[];angleClosure=null;draw();update();});
$('exportDxf').onclick=()=>{const mm=p=>({x:Math.round(p.x*1000),y:Math.round(-p.y*1000)});let dxf=['0','SECTION','2','ENTITIES'];for(let i=0;i<points.length;i++){const a=mm(points[i]),b=mm(points[(i+1)%points.length]);dxf.push('0','LINE','8','КОНТУР','10',a.x,'20',a.y,'30','0','11',b.x,'21',b.y,'31','0');}diagonals.forEach(d=>{const a=mm(points[d.from]),b=mm(points[d.to]);dxf.push('0','LINE','8','ДИАГОНАЛИ','10',a.x,'20',a.y,'30','0','11',b.x,'21',b.y,'31','0');});planObjects.forEach(o=>{const p=mm(o);dxf.push('0','CIRCLE','8','ОБЪЕКТЫ','10',p.x,'20',p.y,'30','0','40',o.type==='pipe'?'30':'15');});dxf.push('0','ENDSEC','0','EOF');const blob=new Blob([dxf.join('\r\n')],{type:'application/dxf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(($('projectName').value||'потолок').replace(/[^а-яёa-z0-9_-]/gi,'_'))+'.dxf';a.click();URL.revokeObjectURL(a.href);toast('DXF-файл сформирован: проверьте требования производства');};
renderObjectRows();
renderObjectManager();
update();

var catalogItems=[
  {id:'msd-classic-mat',type:'Полотно MSD',name:'MSD Classic — белый мат / сатин',article:'MSD-CL-303',price:620,unit:'₽ / м²',desc:'ПВХ-плёнка, белый 303. Ширины: 1,5; 1,8; 2; 2,4; 2,7; 2,8; 3,2; 3,6; 4; 4,5; 5 м. Линейка Classic.',apply:()=>{$('canvasType').value='mat';$('canvasColor').value='Белый';$('canvasPrice').value=620}},
  {id:'msd-classic-gloss',type:'Полотно MSD',name:'MSD Classic — белый глянец',article:'MSD-CLG-303',price:700,unit:'₽ / м²',desc:'ПВХ-плёнка, белый 303. Ширины: 1,5; 2; 2,4; 2,7; 2,8; 3,2; 3,6; 4; 4,5; 5 м. Линейка Classic.',apply:()=>{$('canvasType').value='gloss';$('canvasColor').value='Белый';$('canvasPrice').value=700}},
  {id:'msd-premium-white',type:'Полотно MSD',name:'MSD Premium — белый мат / сатин',article:'MSD-PR-303',price:740,unit:'₽ / м²',desc:'ПВХ-плёнка, белый 303. Ширины: от 1,4 до 5 м; мат и сатин. Линейка Premium.',apply:()=>{$('canvasType').value='mat';$('canvasColor').value='Белый';$('canvasPrice').value=740}},
  {id:'msd-premium-gloss',type:'Полотно MSD',name:'MSD Premium — цветной глянец',article:'MSD-PRG',price:980,unit:'₽ / м²',desc:'ПВХ-плёнка; цветной лак выпускается в Premium. Заявленные ширины: 1,4–5 м, набор зависит от цвета.',apply:()=>{$('canvasType').value='gloss';$('canvasPrice').value=980}},
  {id:'msd-premium-color',type:'Полотно MSD',name:'MSD Premium — цветной мат / сатин',article:'MSD-PRC',price:860,unit:'₽ / м²',desc:'ПВХ-плёнка. Основные ширины: 2,7 и 3,2 м; для части цветов также 4 и 5 м. Линейка Premium.',apply:()=>{$('canvasType').value='satin';$('canvasPrice').value=860}},
  {id:'msd-translucent',type:'Полотно MSD',name:'MSD Premium — транслюцент',article:'MSD-TR-303',price:1150,unit:'₽ / м²',desc:'Светорассеивающая ПВХ-плёнка для запотолочной подсветки. Доступна в ширинах 3,2 и 5 м; также есть прозрачная 3,2 м.',apply:()=>{$('canvasType').value='translucent';$('canvasColor').value='Белый';$('canvasPrice').value=1150}},
  {id:'msd-exclusive',type:'Полотно MSD',name:'MSD Premium — эксклюзивные фактуры',article:'MSD-EX',price:1450,unit:'₽ / м²',desc:'Перламутр 3,2 м, Galaxy 3,2 м, фактурный мат 2,7–5 м, заводская фотопечать 2,7/3,2 м, «дерево» и Art Deco.',apply:()=>{$('canvasType').value='mat';$('canvasPrice').value=1450}},
  {id:'msd-cold',type:'Полотно MSD',name:'MSD — холодная натяжка',article:'MSD-COLD-303',price:1250,unit:'₽ / м²',desc:'Матовое белое ПВХ-полотно 303 шириной 3,2 м для монтажа без прогрева. Уточняйте совместимый профиль и технологию у поставщика.',apply:()=>{$('canvasType').value='mat';$('canvasColor').value='Белый';$('canvasPrice').value=1250}},
  {id:'msd-evolution',type:'Полотно MSD',name:'MSD Evolution — белая коллекция',article:'MSD-EVO-303',price:920,unit:'₽ / м²',desc:'ПВХ-плёнка белого цвета 303: мат, сатин и глянец. Линейка Evolution; точный набор ширин и наличие проверяйте у дилера.',apply:()=>{$('canvasType').value='mat';$('canvasColor').value='Белый';$('canvasPrice').value=920}},
  {id:'mat-canvas',type:'Полотно',name:'Матовое ПВХ-полотно',article:'PVC-MAT',price:690,unit:'₽ / м²',desc:'Состав: поливинилхлоридная плёнка. Типичная ширина рулона: 1,5–5 м; при большей ширине используется сварной шов.',apply:()=>{$('canvasType').value='mat';$('canvasPrice').value=690}},
  {id:'satin-canvas',type:'Полотно',name:'Сатиновое ПВХ-полотно',article:'PVC-SAT',price:790,unit:'₽ / м²',desc:'Состав: ПВХ-плёнка с сатиновой фактурой. Типичная ширина рулона: 1,5–5 м.',apply:()=>{$('canvasType').value='satin';$('canvasPrice').value=790}},
  {id:'gloss-canvas',type:'Полотно',name:'Глянцевое ПВХ-полотно',article:'PVC-GLS',price:850,unit:'₽ / м²',desc:'Состав: ПВХ-плёнка с отражающей лаковой поверхностью. Типичная ширина рулона: 1,5–5 м.',apply:()=>{$('canvasType').value='gloss';$('canvasPrice').value=850}},
  {id:'translucent-canvas',type:'Полотно',name:'Светопрозрачное ПВХ-полотно',article:'PVC-TRN',price:1150,unit:'₽ / м²',desc:'Состав: светорассеивающая ПВХ-плёнка для запотолочной подсветки. Типичная ширина: до 3,5 м; требует расчёта светового короба.',apply:()=>{$('canvasType').value='translucent';$('canvasPrice').value=1150}},
  {id:'acoustic-canvas',type:'Полотно',name:'Акустическое перфорированное ПВХ',article:'PVC-ACT',price:1350,unit:'₽ / м²',desc:'Состав: перфорированная ПВХ-плёнка; для выраженного эффекта применяется вместе со звукопоглощающим слоем. Типичная ширина: 1,5–5 м.',apply:()=>{$('canvasType').value='acoustic';$('canvasPrice').value=1350}},
  {id:'fabric-canvas',type:'Полотно',name:'Тканевое полотно',article:'FAB-PL',price:1650,unit:'₽ / м²',desc:'Состав: полиэфирная ткань с полиуретановой пропиткой. Типичная ширина рулона: 1,5–5 м; у отдельных коллекций — до 5,1 м.',apply:()=>{$('canvasType').value='fabric';$('canvasPrice').value=1650}},
  {id:'lumfer-euro02',type:'Профиль · LumFer',name:'EuroLumFer 02',article:'LF-EU02',price:null,unit:'по запросу',desc:'Алюминиевый теневой профиль для гарпунной системы; серия LumFer для теневого примыкания.',apply:()=>{$('profileType').value='Теневой'}},
  {id:'lumfer-volat',type:'Профиль · LumFer',name:'LumFer Volat / Volat mini',article:'LF-VOLAT',price:null,unit:'по запросу',desc:'Парящая система LumFer для контурной LED-подсветки.',apply:()=>{$('profileType').value='Парящий'}},
  {id:'lumfer-un',type:'Профиль · LumFer',name:'LumFer UN',article:'LF-UN',price:null,unit:'по запросу',desc:'Универсальная ниша и переход уровня; применяется в двухуровневых конструкциях.',apply:()=>{$('profileType').value='Многоуровневый'}},
  {id:'lumfer-track',type:'Профиль · LumFer',name:'LumFer Track 23 / 25',article:'LF-TRACK',price:null,unit:'по запросу',desc:'Интеграция трековых систем: Track 23 Light/23 и Track 25 Light/25.',apply:()=>{$('profileType').value='Трековая система'}},
  {id:'lumfer-pdk',type:'Профиль · LumFer',name:'LumFer PDK60 NEW',article:'LF-PDK60',price:null,unit:'по запросу',desc:'Переход для карнизной ниши; алюминий, длина 2 м, рекомендуемый опуск от 6 см.',apply:()=>{$('profileType').value='Карнизный'}},
  {id:'eurokraab',type:'Профиль · KRAAB',name:'EuroKRAAB',article:'EK-BASE',price:null,unit:'по запросу',desc:'Теневой алюминиевый профиль с тёмным гарпунным узлом для ровного чёрного зазора.',apply:()=>{$('profileType').value='Теневой'}},
  {id:'eurokraab-strong',type:'Профиль · KRAAB',name:'EuroKRAAB Strong',article:'EK-STRONG',price:null,unit:'по запросу',desc:'Усиленная версия для больших площадей, керамогранита и неровных стен.',apply:()=>{$('profileType').value='Теневой'}},
  {id:'slott',type:'Профиль · KRAAB',name:'SLOTT / SLOTT R',article:'SLOTT-R',price:null,unit:'по запросу',desc:'Световые, нишевые и трековые решения; SLOTT R рассчитан на ПВХ и тканевые полотна.',apply:()=>{$('profileType').value='Световая система'}},
  {id:'flexy-euro',type:'Профиль · FLEXYPRO',name:'Flexy EURO 05',article:'EURO-05',price:null,unit:'по запросу',desc:'Алюминиевый стеновой теневой профиль для гарпунной системы; теневой зазор 7,7 мм, длина 2 м.',apply:()=>{$('profileType').value='Теневой'}},
  {id:'flexy-fly',type:'Профиль · FLEXYPRO',name:'Flexy FLY',article:'FLY',price:null,unit:'по запросу',desc:'Стеновой парящий профиль для натяжных потолков с гарпунной системой.',apply:()=>{$('profileType').value='Парящий'}},
  {id:'flexy-line8',type:'Профиль · FLEXYPRO',name:'Flexy LINE 8',article:'LINE-8',price:null,unit:'по запросу',desc:'Система для цельных интегрированных световых линий.',apply:()=>{$('profileType').value='Световая система'}},
  {id:'flexy-gardina',type:'Профиль · FLEXYPRO',name:'Flexy GARDINA2 05',article:'GARDINA2-05',price:null,unit:'по запросу',desc:'Карнизное решение из линейки Flexy IZI для натяжных и тканевых потолков.',apply:()=>{$('profileType').value='Карнизный'}},
  {id:'borzz',type:'Профиль · BORZZ',name:'BORZZ SERIES',article:'BORZZ',price:null,unit:'по запросу',desc:'Отдельная дизайнерская серия FLEXYPRO. Подбор конкретного профиля и комплектации требуется по проекту.',apply:()=>toast('Для BORZZ выберите конкретную систему по каталогу поставщика и внесите цену в проект')},
  {id:'pvc',type:'Профиль',name:'Стандартный ПВХ-багет',article:'ПВХ-01',price:95,unit:'₽ / п.м.',desc:'Базовый стеновой профиль для гарпунной системы.',apply:()=>{$('profileType').value='Стандартный ПВХ';$('profilePrice').value=95}},
  {id:'al',type:'Профиль',name:'Алюминиевый стеновой профиль',article:'AL-02',price:240,unit:'₽ / п.м.',desc:'Жёсткий профиль для стандартных и сложных контуров.',apply:()=>{$('profileType').value='Алюминиевый';$('profilePrice').value=240}},
  {id:'shadow',type:'Профиль',name:'Теневой профиль',article:'SH-03',price:430,unit:'₽ / п.м.',desc:'Создаёт теневой зазор по периметру без вставки.',apply:()=>{$('profileType').value='Теневой';$('profilePrice').value=430}},
  {id:'float',type:'Профиль',name:'Парящий профиль',article:'FL-04',price:680,unit:'₽ / п.м.',desc:'Профиль с полкой для LED-подсветки по контуру.',apply:()=>{$('profileType').value='Парящий';$('profilePrice').value=680}},
  {id:'line',type:'Световая система',name:'Световая линия',article:'LL-20',price:2100,unit:'₽ / м',desc:'Профиль, рассеиватель и LED-комплект для линии света.',apply:()=>{$('lightLinePrice').value=2100}},
  {id:'spot',type:'Светильник',name:'Встраиваемый LED-светильник',article:'SP-12',price:850,unit:'₽ / шт.',desc:'Точечный светильник с закладной и термокольцом.',apply:()=>{$('spotPrice').value=850}},
  {id:'insert',type:'Вставка',name:'Маскировочная вставка',article:'TL-01',price:35,unit:'₽ / п.м.',desc:'Закрывает технологический зазор между стеной и полотном.',apply:()=>toast('Позиция учтена в справочнике; добавьте цену в расходники при настройке сметы')},
  {id:'pipe',type:'Комплектующие',name:'Обвод трубы',article:'TR-08',price:650,unit:'₽ / шт.',desc:'Термокольцо и монтажный комплект для обхода трубы.',apply:()=>{$('pipePrice').value=650}}
];
var catalogFilter='Все';
function renderCatalog(){const q=($('catalogSearch').value||'').toLowerCase(),types=['Все',...new Set(catalogItems.map(x=>x.type))];$('catalogFilters').innerHTML=types.map(x=>`<button class="${x===catalogFilter?'active':''}" data-catalog-filter="${x}">${x}</button>`).join('');$('catalogFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{catalogFilter=b.dataset.catalogFilter;renderCatalog()});const items=catalogItems.filter(x=>(catalogFilter==='Все'||x.type===catalogFilter)&&(`${x.name} ${x.article}`).toLowerCase().includes(q));$('catalogGrid').innerHTML=items.map(x=>`<article class="catalog-card"><span class="catalog-type">${x.type.toUpperCase()} · ${x.article}</span><h3>${x.name}</h3><p>${x.desc}</p><div class="catalog-footer"><strong>${x.price===null?'Цена по запросу':money(x.price)} <small>${x.price===null?'':x.unit.replace('₽ ','')}</small></strong><button data-catalog-item="${x.id}">В проект</button></div></article>`).join('')||'<p class="hint">Ничего не найдено.</p>';$('catalogGrid').querySelectorAll('[data-catalog-item]').forEach(b=>b.onclick=()=>{const item=catalogItems.find(x=>x.id===b.dataset.catalogItem);item.apply();update();toast('Параметры добавлены в текущий проект')});}
$('catalogSearch').addEventListener('input',renderCatalog);
renderCatalog();
// Временная единая стартовая цена до подключения прайса Domus Studio.
catalogItems.forEach(item=>{item.price=100});
renderCatalog();
['canvasPrice','profilePrice','installPrice','spotPrice','lightLinePrice','chandelierPrice','pipePrice','lightPointPrice'].forEach(id=>{if($(id))$(id).value=100});
update();

// Быстрые производственные сценарии.
var roomTemplates={rectangle:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],lshape:[{x:0,y:0},{x:6,y:0},{x:6,y:2},{x:4,y:2},{x:4,y:5},{x:0,y:5}],ushape:[{x:0,y:0},{x:7,y:0},{x:7,y:5},{x:5,y:5},{x:5,y:2},{x:2,y:2},{x:2,y:5},{x:0,y:5}],bay:[{x:0,y:0},{x:5,y:0},{x:6,y:1},{x:6.4,y:2.5},{x:6,y:4},{x:5,y:5},{x:0,y:5}],column:[{x:0,y:0},{x:6,y:0},{x:6,y:5},{x:3.8,y:5},{x:3.8,y:3.8},{x:2.5,y:3.8},{x:2.5,y:5},{x:0,y:5}]};
document.querySelectorAll('[data-room-template]').forEach(b=>b.onclick=()=>{points=structuredClone(roomTemplates[b.dataset.roomTemplate]);planObjects=[];diagonals=[];angleClosure=null;selected=null;zoom=1;draw();update();toast('Шаблон помещения применён')});
var metaBase=objectMeta;
objectMeta=function(type){return {vent:{name:'Вентиляция / люк',color:'#5b8bbd',mark:'▣'},cornice:{name:'Скрытый карниз',color:'#a57943',mark:'⌐'},track:{name:'Трековая точка',color:'#383d52',mark:'═'},separator:{name:'Разделитель полотен',color:'#7b5caa',mark:'║'}}[type]||metaBase(type)};
function renderPreflight(){const t=totals(),items=[];const add=(state,title,detail)=>items.push({state,title,detail});add(points.length>=3?'ok':'error','Контур помещения',points.length>=3?'Контур содержит '+points.length+' вершин.':'Добавьте минимум 3 вершины.');add(!selfIntersects()?'ok':'error','Пересечения линий',selfIntersects()?'Контур пересекается.':'Самопересечений нет.');add(t.a>=1?'ok':'error','Площадь',t.a>=1?fmt(t.a)+' м².':'Площадь слишком мала.');add(angleClosure===null||angleClosure<.03?'ok':'warn','Замыкание по углам',angleClosure===null?'Не проверялось по углам.':angleClosure<.03?'Расхождение в допуске.':'Расхождение '+fmt(angleClosure)+' м.');add(diagonals.length?'ok':'warn','Контрольные диагонали',diagonals.length?'Добавлено: '+diagonals.length+'.':'Для сложного контура добавьте диагонали.');add($('clientName').value?'ok':'warn','Данные клиента',$('clientName').value?'Клиент указан.':'Не заполнено имя клиента.');add($('canvasPrice').value>0&&$('profilePrice').value>0?'ok':'error','Комплектация и цены','Полотно и профиль '+($('canvasPrice').value>0&&$('profilePrice').value>0?'имеют цену.':'требуют цены.'));add(!$('profileType').value?'error':'ok','Тип профиля',$('profileType').value||'Не выбран.');const errors=items.filter(x=>x.state==='error').length,warns=items.filter(x=>x.state==='warn').length;$('preflightSummary').textContent=errors?`Есть ${errors} критических ошибок`:(warns?`Проект готов с ${warns} предупреждениями`:'Проект готов к передаче на производство');$('preflightList').innerHTML=items.map(x=>`<div class="preflight-item ${x.state}"><span class="mark">${x.state==='ok'?'✓':x.state==='warn'?'!':'×'}</span><div><b>${x.title}</b><small>${x.detail}</small></div></div>`).join('');}
$('runPreflight').onclick=renderPreflight;
function quotePreset(kind){const map={economy:{canvasType:'mat',canvasPrice:590,profileType:'Стандартный ПВХ',profilePrice:95,installPrice:450,markup:15},standard:{canvasType:'satin',canvasPrice:790,profileType:'Алюминиевый',profilePrice:240,installPrice:550,markup:20},shadow:{canvasType:'mat',canvasPrice:950,profileType:'Теневой',profilePrice:480,installPrice:700,markup:25},light:{canvasType:'translucent',canvasPrice:1150,profileType:'Световая система',profilePrice:900,installPrice:850,markup:25}}[kind];Object.entries(map).forEach(([id,value])=>$(id).value=value);if(kind==='light'){$('lightLine').value=Math.max(2,Math.round(perimeter()/4));}update();toast('Шаблон сметы применён')}
$('quoteEconomy').onclick=()=>quotePreset('economy');$('quoteStandard').onclick=()=>quotePreset('standard');$('quoteShadow').onclick=()=>quotePreset('shadow');$('quoteLight').onclick=()=>quotePreset('light');
$('exportProject').onclick=()=>{const blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(($('projectName').value||'project').replace(/[^а-яёa-z0-9_-]/gi,'_'))+'.json';a.click();URL.revokeObjectURL(a.href);toast('Резервная копия скачана')};
$('importProject').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{apply(JSON.parse(r.result));toast('Проект восстановлен из копии')}catch{toast('Не удалось прочитать файл проекта')}};r.readAsText(file);e.target.value='';});
